name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set Up Compilers
      run: |
        sudo apt install -y g++-10
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Install
      run: sudo cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target install

    - name: Configure Tests
      run: cmake tests
      
    - name: Build Tests
      run: cmake --build . --parallel

    - name: Test
      run: ctest
